spring:
    output:
        ansi:
            enabled: always
    jpa:
        hibernate.ddl-auto: create
        properties:
            hibernate:
                namingStrategy: org.hibernate.cfg.DefaultNamingStrategy
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/bookings
        username: root
        password: rootroot
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
#    jackson:
#        date-format: "dd-MM-yyyy"
server:
    port: 8080
management:
    port: 9000

